### ISSUE TITLE
Old police belts 

### ISSUE THREAD

**Issue by Turks1** [ScottUK/ladojrp-issues#9] opened 2021-12-16 19:35 UTC
**Describe the feature you'd like implemented**
A clear and concise description of what you want implemented into the server.

**Link to the resource if it already exists**
If it already exists, post the link to the resource here.

**Additional context**

**Comment by ScottUK** [comment] 2021-12-23 05:42
Duplicate of #10 , closing this.

**Closed by ScottUK** 2021-12-23 05:42 UTC
Labels: Class: enhancement, Status: invalid
