### ISSUE TITLE
Bug Report: Command's Bug (2)

### ISSUE THREAD

**Issue by CharlieHunter1** [ScottUK/ladojrp-issues#48] opened 2022-01-03 12:04 UTC
**Description of the problem**
A number of commands are currently broken:
- /carry
- /drag
- /th and /takehostage
- Emote Script
- Ragdoll Script (U)

**Reproduction steps**
Use the commands on people to reproduce

**Expected behavior**
For the commands to work properly i.e Carry, Drag, Takehostage, Carry out the Emotes, Ragdoll

**Screenshots**
N/A

**Additional information**
YouTube Video - https://youtu.be/U-fdAlr9x6g

**Comment by ScottUK** [comment] 2022-01-03 18:10
Duplicate of #45 , but I'll close that one since this is formatted better. :)

**Comment by ScottUK** [comment] 2022-01-03 18:12
Looks like this is an issue with the latest GTA update and attaching people together. I might have to overhaul these commands. 🤔

**Comment by ScottUK** [comment] 2022-01-05 18:32
Ragdoll cannot be fixed, but everything else should be good. :)

**Closed by ScottUK** 2022-01-05 18:32 UTC
Labels: Class: enhancement, Priority: critical, Scope: scripts
