### ISSUE TITLE
Durability of cars

### ISSUE THREAD

**Issue by Brightttttt** [ScottUK/ladojrp-issues#94] opened 2022-01-17 14:58 UTC
So with the current system we have that makes our cars start to smoke and break down within 1 or 2 minutes is good but it is a little unrealistic since when you just tap something your car starts to smoke and breaks down instantly or lets you drive a small distance before it breaks down so I suggest that making it more durable would be really cool to see as with the current state it is a little unrealistic. I would also like to see some cars that are not meant to be on the dirt be able to drive on the dirt a little longer and that it slides a little less as it almost looks like you are driving on ice the second you hit the dirt.

**Comment by ScottUK** [comment] 2022-01-17 16:51
The durability is pretty realistic, in real life cars are often written off after one collision. I will tweak it a bit, but in terms of driving on dirt that issue already exists here: #22 .  So I'll close this as it's a duplicate of that. :)

**Closed by ScottUK** 2022-01-17 16:51 UTC
